apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stuckoverbug-client-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DevOps-Tim1-CDEF/Frontend.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: server

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      # - PruneLast=true
      # # - ServerSideApply=true
      # - Replace=true

    automated:
      selfHeal: true
      prune: true
# operation:
#   sync:
#     syncStrategy:
#       hook:
#         force: true
