apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stuckoverbug-client-hpa
  namespace: client
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stuckoverbug-client
  minReplicas: 2
  maxReplicas: 30
  metrics: # Corrected indentation here
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
